package com.Amazing.entity;
// Generated Oct 14, 2023, 12:05:32 AM by Hibernate Tools 4.3.6.Final

import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "CATEGORY", schema = "dbo", catalog = "AMAZING_TMDT")
public class Category {

	private String cateId;
	private Store store;
	private String cateName;
	private List<Product> products;

	public Category() {
	}

	public Category(Store store, String cateName) {
		this.store = store;
		this.cateName = cateName;
	}

	public Category(Store store, String cateName, List<Product> products) {
		this.store = store;
		this.cateName = cateName;
		this.products = products;
	}

	@Id
	@Column(name = "CATE_ID", unique = true, nullable = false, length = 36)
	public String getCateId() {
		return this.cateId;
	}

	public void setCateId(String cateId) {
		this.cateId = cateId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORE_ID", nullable = false)
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "CATE_NAME", nullable = false)
	public String getCateName() {
		return this.cateName;
	}

	public void setCateName(String cateName) {
		this.cateName = cateName;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public List<Product> getProducts() {
		return this.products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}

}
