package com.Amazing.entity;
// Generated Oct 14, 2023, 12:05:32 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * InvoiceDetail generated by hbm2java
 */
@Entity
@Table(name = "INVOICE_DETAIL", schema = "dbo", catalog = "AMAZING_TMDT")
public class InvoiceDetail {

	private InvoiceDetailId id;
	private Invoice invoice;
	private Type type;
	private int invoiceDtPrice;
	private int invoiceDtQuantity;

	public InvoiceDetail() {
	}

	public InvoiceDetail(InvoiceDetailId id, Invoice invoice, Type type, int invoiceDtPrice, int invoiceDtQuantity) {
		this.id = id;
		this.invoice = invoice;
		this.type = type;
		this.invoiceDtPrice = invoiceDtPrice;
		this.invoiceDtQuantity = invoiceDtQuantity;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "invoiceId", column = @Column(name = "INVOICE_ID", nullable = false)),
			@AttributeOverride(name = "typeId", column = @Column(name = "TYPE_ID", nullable = false, length = 36)) })
	public InvoiceDetailId getId() {
		return this.id;
	}

	public void setId(InvoiceDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVOICE_ID", nullable = false, insertable = false, updatable = false)
	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TYPE_ID", nullable = false, insertable = false, updatable = false)
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Column(name = "INVOICE_DT_PRICE", nullable = false)
	public int getInvoiceDtPrice() {
		return this.invoiceDtPrice;
	}

	public void setInvoiceDtPrice(int invoiceDtPrice) {
		this.invoiceDtPrice = invoiceDtPrice;
	}

	@Column(name = "INVOICE_DT_QUANTITY", nullable = false)
	public int getInvoiceDtQuantity() {
		return this.invoiceDtQuantity;
	}

	public void setInvoiceDtQuantity(int invoiceDtQuantity) {
		this.invoiceDtQuantity = invoiceDtQuantity;
	}

}
