package com.Amazing.entity;
// Generated Oct 14, 2023, 12:05:32 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * InvoiceDetailId generated by hbm2java
 */
@Embeddable
public class InvoiceDetailId {

	private int invoiceId;
	private String typeId;

	public InvoiceDetailId() {
	}

	public InvoiceDetailId(int invoiceId, String typeId) {
		this.invoiceId = invoiceId;
		this.typeId = typeId;
	}

	@Column(name = "INVOICE_ID", nullable = false)
	public int getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(int invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "TYPE_ID", nullable = false, length = 36)
	public String getTypeId() {
		return this.typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceDetailId))
			return false;
		InvoiceDetailId castOther = (InvoiceDetailId) other;

		return (this.getInvoiceId() == castOther.getInvoiceId())
				&& ((this.getTypeId() == castOther.getTypeId()) || (this.getTypeId() != null
						&& castOther.getTypeId() != null && this.getTypeId().equals(castOther.getTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInvoiceId();
		result = 37 * result + (getTypeId() == null ? 0 : this.getTypeId().hashCode());
		return result;
	}

}
