package com.Amazing.entity;
// Generated Oct 14, 2023, 12:05:32 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.ToString;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "INVOICE", schema = "dbo", catalog = "AMAZING_TMDT")
@ToString
public class Invoice {

	private Integer invoiceId;
	private Shipper shipper;
	private Users users;
	private String invoiceAddress;
	private Date invoiceDate;
	private String invoiceNote;
	private Boolean invoiceShippingstatus;
	private List<InvoiceDetail> invoiceDetails;

	public Invoice() {
	}

	public Invoice(Users users, String invoiceAddress, Date invoiceDate) {
		this.users = users;
		this.invoiceAddress = invoiceAddress;
		this.invoiceDate = invoiceDate;
	}

	public Invoice(Shipper shipper, Users users, String invoiceAddress, Date invoiceDate, String invoiceNote,
			Boolean invoiceShippingstatus, List<InvoiceDetail> invoiceDetails) {
		this.shipper = shipper;
		this.users = users;
		this.invoiceAddress = invoiceAddress;
		this.invoiceDate = invoiceDate;
		this.invoiceNote = invoiceNote;
		this.invoiceShippingstatus = invoiceShippingstatus;
		this.invoiceDetails = invoiceDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "INVOICE_ID", unique = true, nullable = false)
	public Integer getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Integer invoiceId) {
		this.invoiceId = invoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SHIPPER_ID")
	public Shipper getShipper() {
		return this.shipper;
	}

	public void setShipper(Shipper shipper) {
		this.shipper = shipper;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PHONE", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "INVOICE_ADDRESS", nullable = false)
	public String getInvoiceAddress() {
		return this.invoiceAddress;
	}

	public void setInvoiceAddress(String invoiceAddress) {
		this.invoiceAddress = invoiceAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INVOICE_DATE", nullable = false, length = 23)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Column(name = "INVOICE_NOTE")
	public String getInvoiceNote() {
		return this.invoiceNote;
	}

	public void setInvoiceNote(String invoiceNote) {
		this.invoiceNote = invoiceNote;
	}

	@Column(name = "INVOICE_SHIPPINGSTATUS")
	public Boolean getInvoiceShippingstatus() {
		return this.invoiceShippingstatus;
	}

	public void setInvoiceShippingstatus(Boolean invoiceShippingstatus) {
		this.invoiceShippingstatus = invoiceShippingstatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
	public List<InvoiceDetail> getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(List<InvoiceDetail> invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}

}
