package com.Amazing.entity;
//Generated Oct 14, 2023, 12:05:32 AM by Hibernate Tools 4.3.6.FinalF

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.ToString;

import org.hibernate.annotations.GenericGenerator;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT", schema = "dbo", catalog = "AMAZING_TMDT")
@ToString
public class Product {

	private String productId;
	private Category category;
	private String productName;
	private Integer productMinprice;
	private Integer productMaxprice;
	private String productDescription;
	private List<Type> types = new ArrayList<>();

	public Product() {
	}

	public Product(Category category, String productName) {
		this.category = category;
		this.productName = productName;
	}

	public Product(Category category, String productName, String productDescription, List<Type> types) {
		this.category = category;
		this.productName = productName;
		this.productDescription = productDescription;
		this.types = types;
	}
	

	@Id
	@Column(name = "PRODUCT_ID", unique = true, nullable = false, length = 36)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATE_ID", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "PRODUCT_NAME", nullable = false)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "PRODUCT_MINPRICE")
	public Integer getProductMinprice() {
		return productMinprice;
	}

	public void setProductMinprice(Integer productMinprice) {
		this.productMinprice = productMinprice;
	}

	@Column(name = "PRODUCT_MAXPRICE")
	public Integer getProductMaxprice() {
		return productMaxprice;
	}

	public void setProductMaxprice(Integer productMaxprice) {
		this.productMaxprice = productMaxprice;
	}

	@Column(name = "PRODUCT_DESCRIPTION")
	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public List<Type> getTypes() {
		return this.types;
	}

	public void setTypes(List<Type> types) {
		this.types = types;
	}

	public Product(String productId, Category category, String productName, Integer productMinprice, Integer productMaxprice,
			String productDescription, List<Type> types, List<InvoiceDetail> invoiceDetails) {
		super();
		this.productId = productId;
		this.category = category;
		this.productName = productName;
		this.productMinprice = productMinprice;
		this.productMaxprice = productMaxprice;
		this.productDescription = productDescription;
		this.types = types;
	}

	

}