package com.Amazing.entity;
// Generated Sep 29, 2023, 7:50:24 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT", schema = "dbo", catalog = "AMAZING_TMDT")
public class Product {

	private String productId;
	private Category category;
	private String productName;
	private String productDescription;
	private Set<Type> types = new HashSet<Type>(0);
	private Set<InvoiceDetail> invoiceDetails = new HashSet<InvoiceDetail>(0);

	public Product() {
	}

	public Product(Category category, String productName) {
		this.category = category;
		this.productName = productName;
	}

	public Product(Category category, String productName, String productDescription, Set<Type> types,
			Set<InvoiceDetail> invoiceDetails) {
		this.category = category;
		this.productName = productName;
		this.productDescription = productDescription;
		this.types = types;
		this.invoiceDetails = invoiceDetails;
	}

	@Id
	@Column(name = "PRODUCT_ID", unique = true, nullable = false, length = 36)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATE_ID", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "PRODUCT_NAME", nullable = false)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "PRODUCT_DESCRIPTION")
	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Type> getTypes() {
		return this.types;
	}

	public void setTypes(Set<Type> types) {
		this.types = types;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<InvoiceDetail> getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(Set<InvoiceDetail> invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}

}
