/*
 * Created on 2023-10-06 ( 00:22:52 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.Amazing.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;




/**
 * JPA entity class for "Shipper"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="SHIPPER", schema="dbo", catalog="AMAZING_TMDT" )
public class Shipper implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="SHIPPER_ID", nullable=false, length=36)
    private String     shipperId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SHIPPER_PASSWORD", nullable=false, length=50)
    private String     shipperPassword ;

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Column(name="SHIPPER_DATE", nullable=true)
    private Date       shipperDate ;

    @Column(name="SHIPPER_AVATAR", nullable=false, length=2147483647)
    private String     shipperAvatar ;

    @Column(name="SHIPPER_PHONE", nullable=false, length=11)
    private String     shipperPhone ;

    @Column(name="SHIPPER_LICENSE", nullable=false, length=2147483647)
    private String     shipperLicense ;

    @Column(name="SHIPPER_FULLNAME", nullable=false, length=264)
    private String     shipperFullname ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="shipper")
    private List<Invoice> listOfInvoice ; 


    /**
     * Constructor
     */
    public Shipper() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setShipperId( String shipperId ) {
        this.shipperId = shipperId ;
    }
    public String getShipperId() {
        return this.shipperId;
    }

    public void setShipperPassword( String shipperPassword ) {
        this.shipperPassword = shipperPassword ;
    }
    public String getShipperPassword() {
        return this.shipperPassword;
    }

    public void setShipperDate( Date shipperDate ) {
        this.shipperDate = shipperDate ;
    }
    public Date getShipperDate() {
        return this.shipperDate;
    }

    public void setShipperAvatar( String shipperAvatar ) {
        this.shipperAvatar = shipperAvatar ;
    }
    public String getShipperAvatar() {
        return this.shipperAvatar;
    }

    public void setShipperPhone( String shipperPhone ) {
        this.shipperPhone = shipperPhone ;
    }
    public String getShipperPhone() {
        return this.shipperPhone;
    }

    public void setShipperLicense( String shipperLicense ) {
        this.shipperLicense = shipperLicense ;
    }
    public String getShipperLicense() {
        return this.shipperLicense;
    }

    public void setShipperFullname( String shipperFullname ) {
        this.shipperFullname = shipperFullname ;
    }
    public String getShipperFullname() {
        return this.shipperFullname;
    }

    //--- GETTERS FOR LINKS
    public List<Invoice> getListOfInvoice() {
        return this.listOfInvoice;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(shipperId);
        sb.append("|");
        sb.append(shipperPassword);
        sb.append("|");
        sb.append(shipperDate);
        sb.append("|");
        sb.append(shipperAvatar);
        sb.append("|");
        sb.append(shipperPhone);
        sb.append("|");
        sb.append(shipperLicense);
        sb.append("|");
        sb.append(shipperFullname);
        return sb.toString(); 
    } 

}
